
const azenthyr_Level_One_West = {

    a1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[1,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    a2:{name:"Vothys",terrain:hex_Type.cavern,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[1,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    a3:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[1,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    a4:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[1,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    a5:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[1,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    a6:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[1,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    a7:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[1,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    b1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[2,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    b2:{name:"",terrain:hex_Type.cavern,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[2,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    b3:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[2,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    b4:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[2,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    b5:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[2,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    b6:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[2,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    b7:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[2,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    c1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[3,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    c2:{name:"",terrain:hex_Type.cavern,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[3,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    c3:{name:"",terrain:hex_Type.cavern,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[3,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    c4:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[3,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    c5:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[3,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    c6:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[3,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    c7:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[3,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    d1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[4,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    d2:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[4,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    d3:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[4,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    d4:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[4,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    d5:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[4,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    d6:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[4,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    d7:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[4,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    e1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[5,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    e2:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[5,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    e3:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[5,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    e4:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[5,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    e5:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[5,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    e6:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[5,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    e7:{name:"",terrain:hex_Type.jungle,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[5,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    f1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[6,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    f2:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[6,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    f3:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[6,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    f4:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[6,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    f5:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[6,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    f6:{name:"",terrain:hex_Type.cavern,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[6,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    f7:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[6,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    g1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[7,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    g2:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[7,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    g3:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[7,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    g4:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[7,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    g5:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[7,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    g6:{name:"",terrain:hex_Type.cavern,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[7,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    g7:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[7,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    h1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[8,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    h2:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[8,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    h3:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[8,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    h4:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[8,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    h5:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[8,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    h6:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[8,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    h7:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[8,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    i1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[9,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    i2:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[9,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    i3:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[9,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    i4:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[9,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    i5:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[9,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    i6:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[9,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    i7:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[9,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    j1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[10,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    j2:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[10,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    j3:{name:"Faustervault Cavern",terrain:hex_Type.cavern,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[10,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    j4:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[10,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    j5:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[10,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    j6:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[10,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    j7:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[10,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    k1:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[11,1],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    k2:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[11,2],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    k3:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[11,3],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    k4:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[11,4],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    k5:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[11,5],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    k6:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[11,6],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    k7:{name:"",terrain:hex_Type.rock,cities:[],improvements:[],explored:false, map:"azenthyr_Level_One_West",coordinates:[11,7],special_Resource:{name:'none',economy:0,loyalty:0,stability:0,defense:0, consumption:0,BP_Per_Turn:0,}},
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}

const azenthyr_Level_One_West_Array =
[
    azenthyr_Level_One_West.a1,azenthyr_Level_One_West.a2,azenthyr_Level_One_West.a3,azenthyr_Level_One_West.a4,azenthyr_Level_One_West.a5,azenthyr_Level_One_West.a6,azenthyr_Level_One_West.a7,azenthyr_Level_One_West.b1,azenthyr_Level_One_West.b2,azenthyr_Level_One_West.b3,azenthyr_Level_One_West.b4,azenthyr_Level_One_West.b5,azenthyr_Level_One_West.b6,azenthyr_Level_One_West.b7,azenthyr_Level_One_West.c1,azenthyr_Level_One_West.c2,azenthyr_Level_One_West.c3,azenthyr_Level_One_West.c4,azenthyr_Level_One_West.c5,azenthyr_Level_One_West.c6,azenthyr_Level_One_West.c7,azenthyr_Level_One_West.d1,azenthyr_Level_One_West.d2,azenthyr_Level_One_West.d3,azenthyr_Level_One_West.d4,azenthyr_Level_One_West.d5,azenthyr_Level_One_West.d6,azenthyr_Level_One_West.d7,azenthyr_Level_One_West.e1,azenthyr_Level_One_West.e2,azenthyr_Level_One_West.e3,azenthyr_Level_One_West.e4,azenthyr_Level_One_West.e5,azenthyr_Level_One_West.e6,azenthyr_Level_One_West.e7,azenthyr_Level_One_West.f1,azenthyr_Level_One_West.f2,azenthyr_Level_One_West.f3,azenthyr_Level_One_West.f4,azenthyr_Level_One_West.f5,azenthyr_Level_One_West.f6,azenthyr_Level_One_West.f7,azenthyr_Level_One_West.g1,azenthyr_Level_One_West.g2,azenthyr_Level_One_West.g3,azenthyr_Level_One_West.g4,azenthyr_Level_One_West.g5,azenthyr_Level_One_West.g6,azenthyr_Level_One_West.g7,azenthyr_Level_One_West.h1,azenthyr_Level_One_West.h2,azenthyr_Level_One_West.h3,azenthyr_Level_One_West.h4,azenthyr_Level_One_West.h5,azenthyr_Level_One_West.h6,azenthyr_Level_One_West.h7,azenthyr_Level_One_West.i1,azenthyr_Level_One_West.i2,azenthyr_Level_One_West.i3,azenthyr_Level_One_West.i4,azenthyr_Level_One_West.i5,azenthyr_Level_One_West.i6,azenthyr_Level_One_West.i7,azenthyr_Level_One_West.j1,azenthyr_Level_One_West.j2,azenthyr_Level_One_West.j3,azenthyr_Level_One_West.j4,azenthyr_Level_One_West.j5,azenthyr_Level_One_West.j6,azenthyr_Level_One_West.j7,azenthyr_Level_One_West.k1,azenthyr_Level_One_West.k2,azenthyr_Level_One_West.k3,azenthyr_Level_One_West.k4,azenthyr_Level_One_West.k5,azenthyr_Level_One_West.k6,azenthyr_Level_One_West.k7,
]